### ISSUE TITLE
No error state when nut daemon has gone away

### ISSUE THREAD

**Issue by FoxxMD** [SuperioOne/nut_webgui#3]
If I start up nut_webgui with a properly working nut daemon and then the daemon dies nut_webgui never updates. It logs an error like this:

```
2024-10-02T19:54:41.824179Z ERROR nut_webgui::ups_service::ups_poll_service: Poll service error occurred: ClientError(ParseError("Unexpected variable format"))
```

but the web ui, UPS page, UPS details and info, and data in the API all stay in the last good state. The app should update to at least return a 500 or 404 if this occurs so that I can reliably be notified if the daemon can't be monitored anymore.

**Comment by SuperioOne** [comment]
Thanks for the bug report,

I can replicate the issue on my end. Poll service is missing some logic to handle disconnected services and UPS devices. 

It will be fixed with the next release.

**Comment by SuperioOne** [comment]
Version [`0.4.0`](https://github.com/SuperioOne/nut_webgui/releases/tag/v0.4.0) has been released to fix state issues. Additionally, data API and probes now return error details and HTTP 5xx status codes when NUT daemon is down.

I'm closing the issue for now, but feel free to re-open it if more improvements are needed.
